import "./globals.css";
import { Inter } from "next/font/google";
import { SnackbarError, SnackbarInfo } from "@/components/Alerts";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-center ">
          {children}
          <SnackbarInfo />
          <SnackbarError />
        </main>
      </body>
    </html>
  );
}
